FILES =	Makefile \
	Manual.htm \
	HowToDG.html \
	jpconv.htm \
	tutor-jp.htm \
	tutor-en.htm

#	readme1.X.jp \
#	delegate-ML.jp \
#	SecurityNotice.jp \
#	withSOCKS.jp \
#	ProxyTelnetFtp.jp

files:;	ls -d $(FILES)
